### ISSUE TITLE
Add equivalent SQL queries in README

### ISSUE THREAD

**Issue by salmanasiddiqui** [EugZol/where_exists#2]
For all the examples in README, it would be good to add SQL queries those methods will generate.

**Comment by EugZol** [comment]
Sorry, hadn't time to do that. Closing the issue for now. PRs are welcome.

**Comment by salmanasiddiqui** [comment]
PRs usually come if there is an issue :)

**Comment by EugZol** [comment]
I hope README is good enough if people keep finding and utilizing the gem despite lack of my PRing it :)
