### ISSUE TITLE
Doesn't work with rails 5

### ISSUE THREAD

**Issue by Qwertie-** [EugZol/where_exists#3]
Running bundle install gives 

`    where_exists was resolved to 0.1, which depends on
      rails (< 5, >= 3.2.22)
`

**Comment by mamantoha** [comment]
Hi, @EugZol.
Any plans to update gem for Rails 5 and push a new version to Rubygems?

**Comment by EugZol** [comment]
Hi @mamantoha! Will do that shortly.

**Comment by mamantoha** [comment]
Cool, thanks 👍

**Comment by EugZol** [comment]
Updated version to 1.0.0. Tests are passing with Rails 5 — but if anything doesn't work please report an issue :)

**Comment by fmoudoute** [comment]
Is this working now, it looks like I am having the same error still. 
`NoMethodError (undefined method `where_exists' for #<Class:0x00007fcf84a59b90>)
`

**Comment by EugZol** [comment]
It has been working since the beginning :) This issue is irrelevant to the error you have. You can create a new one if you want — just provide a little bit more details.
